version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
      # context: .
      # dockerfile: ./Dockerfile.dev
    command: 
      # - ./bin/docker/start
      - ./bin/dev
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      EDITOR: vim
      DATABASE_URL: postgres://postgres:@db:5432/tada_development
      DATABASE_TEST_URL: postgres://postgres:@db:5432/tada_test
    depends_on:
      - db
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025" # mailhog dashboard port
